### ISSUE TITLE
sample跑不起来

### ISSUE THREAD

**Issue by Zhouyanga** [HIT-SCIR/ltp-cloud-api-tutorial#10]
![u0no0h4 81e97 w v 38](https://user-images.githubusercontent.com/35602880/38162753-bdd2c008-3519-11e8-8bf8-94209273c55c.png)

**Comment by Zhouyanga** [comment]
按照说明，将api_key改为了自己的，仍然跑不起来。

**Comment by fseasy** [comment]
```
该tutorial中的rest api url均指向ltpapi.voicecloud.cn，为讯飞语音云合作提供的服务，在2015年末服务分离后，其API_KEY并不与ltp-cloud.com通用。故如果您按照上述方式在ltp-cloud.com注册，其得到的API_KEY仅能用于请求api.ltp-cloud.com. 请注意根据实际需求，修改url.
```
URL有没有改呢…… 

---

另外，如果是大规模跑的话，也可以使直接把 ltp 仓库拖下来，编译，在linux下是有server的，直接用那个server部署更好
