### ISSUE TITLE
为什么返回502 bad Gateway

### ISSUE THREAD

**Issue by SkylerHuang** [HIT-SCIR/ltp-cloud-api-tutorial#11]
![image](https://user-images.githubusercontent.com/24433500/39620481-ed5edaaa-4fbd-11e8-84f8-cd9972a0e92f.png)

**Comment by SkylerHuang** [comment]
使用文档似乎没有这个错误

**Comment by liu946** [comment]
统一回复，由于服务器已经迁移https，请把所有请求协议改为https再访问。
