### ISSUE TITLE
{"error_message": "UNAUTHORIZED USER"}

### ISSUE THREAD

**Issue by yuquanle** [HIT-SCIR/ltp-cloud-api-tutorial#6]
我申请账号：已经出现了以下信息，但是还是账号不通过：

Email: | leyuquan@yeah.net
Api_key: | C1Z49568q2KgDQxLMdwQUmEtBupzQYTKWersnGcw
本月流量使用： | 0 bytes
本月剩余流量： | 18.6 GB

请问这是为什么呢

**Comment by lmzl0302** [comment]
我也是，post方式就会出现这样的问题，而get方式没有问题。

**Comment by Guozeqi** [comment]
我也是未授权，使用的python请问是什么原因..

**Comment by liu946** [comment]
#9
