### ISSUE TITLE
请问可否用本地ltp_server得到的结果作为输入？

### ISSUE THREAD

**Issue by FannyChung** [HIT-SCIR/ltp-cloud-api-tutorial#8]
之前用本地LTP分析到了最后一步语义角色，用了自定义词典和词性，请问是否能用之前的结果作为输入到ltp-cloud，得到包括语义依存在内的所有分析结果呢？

**Comment by fseasy** [comment]
你看看这个  https://github.com/HIT-SCIR/ltp-cloud-api-tutorial/blob/master/Python/Customs/LTML.py
是可以到dp的，语义依存没记错的话不依赖SRL

**Comment by liu946** [comment]
目前 LTP cloud 的网络接口仅支持从原始句子进行分析，不支持使用自定义的依赖信息。
