### ISSUE TITLE
401 UNAUTHORIZED 错误

### ISSUE THREAD

**Issue by panzovor** [HIT-SCIR/ltp-cloud-api-tutorial#9]
你好，我在使用 《使用Python语言以POST方式调用REST API示例代码》的相关示例代码的时候会报401错误。T T

**Comment by estelll** [comment]
我也会！而且无论是用python2还是改成python3，那个示例代码都是报这个错。但是在Python/Basic里的simple.py，用python2就可以正常跑。

**Comment by shushengyang** [comment]
蓝瘦，香菇！

**Comment by liu946** [comment]
#11

**Comment by liu946** [comment]
至于 401 UNAUTHORIZED 可能是由于当时服务器不稳定导致的没有注册完成。目前已经修复。
